//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class TwitterDBEntities : DbContext
    {
        public TwitterDBEntities()
            : base("name=TwitterDBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }

        public virtual int AddUser(string user_Id, string password, string fullName, string email)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));

            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));

            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", user_IdParameter, passwordParameter, fullNameParameter, emailParameter);
        }

        public virtual ObjectResult<TwitterLogin_Result> TwitterLogin(string user_Id, string pass)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TwitterLogin_Result>("TwitterLogin", user_IdParameter, passParameter);
        }

        public virtual ObjectResult<GetAllPerson_Result> GetAllPerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPerson_Result>("GetAllPerson");
        }

        public virtual int InsertTweet(string tweetMsg, string user_Id)
        {
            var tweetMsgParameter = tweetMsg != null ?
                new ObjectParameter("TweetMsg", tweetMsg) :
                new ObjectParameter("TweetMsg", typeof(string));

            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTweet", tweetMsgParameter, user_IdParameter);
        }

        public virtual ObjectResult<GetTweets_Result> GetTweets(string user_Id)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTweets_Result>("GetTweets", user_IdParameter);
        }

        public virtual int UpdateUser(string user_Id, string fullName, string email)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));

            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", user_IdParameter, fullNameParameter, emailParameter);
        }

        public virtual int ChangeUserPassword(string user_Id, string password)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeUserPassword", user_IdParameter, passwordParameter);
        }

        public virtual int DeleteUserTweet(string user_Id, Nullable<int> tweet_Id)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var tweet_IdParameter = tweet_Id.HasValue ?
                new ObjectParameter("Tweet_Id", tweet_Id) :
                new ObjectParameter("Tweet_Id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserTweet", user_IdParameter, tweet_IdParameter);
        }

        public virtual int UdpateUserTweet(string user_Id, Nullable<int> tweet_Id, string tMsg)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var tweet_IdParameter = tweet_Id.HasValue ?
                new ObjectParameter("Tweet_Id", tweet_Id) :
                new ObjectParameter("Tweet_Id", typeof(int));

            var tMsgParameter = tMsg != null ?
                new ObjectParameter("TMsg", tMsg) :
                new ObjectParameter("TMsg", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UdpateUserTweet", user_IdParameter, tweet_IdParameter, tMsgParameter);
        }

        public virtual int FollowUser(string user_Id, string followUser)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var followUserParameter = followUser != null ?
                new ObjectParameter("FollowUser", followUser) :
                new ObjectParameter("FollowUser", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FollowUser", user_IdParameter, followUserParameter);
        }

        public virtual ObjectResult<string> GetFollowers(string user_Id)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFollowers", user_IdParameter);
        }

        public virtual ObjectResult<string> GetFollowing(string user_Id)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFollowing", user_IdParameter);
        }

        public virtual int UnFollowUser(string user_Id, string unFollowUser)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));

            var unFollowUserParameter = unFollowUser != null ?
                new ObjectParameter("UnFollowUser", unFollowUser) :
                new ObjectParameter("UnFollowUser", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UnFollowUser", user_IdParameter, unFollowUserParameter);
        }
    }
}
